{{ if and .Values.domain .Values.ingress .Values.ingress.clusterIssuer .Values.ingress.className .Values.ingress.tlsSecretName }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kanidm
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kanidm
            port:
              number: 443
{{ end }}
