apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kanidm-backup
  namespace: {{ .Release.Namespace }}
spec:
  {{- $backupValues := .Values.backup | default dict }}
  {{ if $backupValues.storageClassName }}
  storageClassName: {{ $backupValues.storageClassName }}
  {{ end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $backupValues.storage | default "5Gi" }}
