apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kanidm-db
  namespace: {{ .Release.Namespace }}
spec:
  {{ if .Values.db.storageClassName }}
  storageClassName: {{ .Values.db.storageClassName }}
  {{ end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.storage | default "2Gi" }}
