apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kanidm-db
  namespace: {{ .Release.Namespace }}
spec:
  {{- $dbValues := .Values.db | default dict }}
  {{ if .dbValues.storageClassName }}
  storageClassName: {{ .dbValues.storageClassName }}
  {{ end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .dbValues.storage | default "2Gi" }}
