apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kanidm-backup
  namespace: {{ .Release.Namespace }}
spec:
  {{ if .Values.backup.storageClassName }}
  storageClassName: {{ .Values.backup.storageClassName }}
  {{ end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backup.storage | default "5Gi" }}
